import type { Metadata } from "next";
import LocalFont from "next/font/local";
import "./globals.css";
import Cursor from "@/Components/Cursor";
import React from "react";



const vazir = LocalFont({
  src: [
    {
      path: './fonts/vazir-font-v16.1.0/Vazir-Thin.woff',
      weight: '100',
      style: 'normal',
    },
    {
      path: './fonts/vazir-font-v16.1.0/Vazir-Light.woff',
      weight: '200',
      style: 'normal',
    },
    {
      path: './fonts/vazir-font-v16.1.0/Vazir-Medium.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: './fonts/vazir-font-v16.1.0/Vazir-Bold.woff',
      weight: '500',
      style: 'normal',
    },


  ],
  display: 'swap',
  variable: '--font-vazir',

});
export const metadata: Metadata = {
  title: "doc",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="fa" className={vazir.variable}>
      <body
          className={`antialiased min-h-screen h-screen overflow-hidden`}
      >
      <Cursor/>
      
      {children}
      </body>
      </html>
  );
}
